### PR TITLE
Landing page gallery view

### PR DESCRIPTION
**Pull request by WorkingDada**

### CODE REVIEW

**Comment by mekintown** [comment]
I have refactored and fixed the most necessary features. Here is the list of items you need to fix:

- [ ] Implement the search filter.
- [ ] Fix the z-index of the min and max price, as it is currently behind the image.
- [ ] Implement create button for photographer which navigate photographer to `/galleries/create-gallery` page. You can check the current user role by
`{data: session} = useSession
session.user.data.verification_status === PhotographerStatus.Verified   

// This is how you can navigate photographer to the create page
router.push(/galleries/create-gallery) (router = useRouter() which imported from /router/navigate)
`
Then we can merge :)

Note:
LandingSideBar is now GalleryFilter in /components/Gallery/
GalleryComponent is now GalleryCard in /components/Gallery/
SearchBar is now in /components/Gallery/

**Review by mekintown — CHANGES_REQUESTED** [review]
I have refactored and fixed the most necessary features. Here is the list of items you need to fix:

- [x] Implement the search filter.
- [x] Fix the z-index of the min and max price, as it is currently behind the image.
- [x] Implement create button for photographer which navigate photographer to /galleries/create-gallery page. You can check the current user role by

```ts
{data: session} = useSession
session.user.data.verification_status === PhotographerStatus.Verified
// This is how you can navigate photographer to the create page
router.push(/galleries/create-gallery) (router = useRouter() which imported from /router/navigate)
```
Then we can merge :)

Note:
LandingSideBar is now GalleryFilter in /components/Gallery/
GalleryComponent is now GalleryCard in /components/Gallery/
SearchBar is now in /components/Gallery/

**Comment by WorkingDada** [comment]
42crbn

**Comment by mekintown** [comment]
looks good  💖

**Pull request merged**
