### PR TITLE
Adding profile view page

### PR DESCRIPTION
**Pull request by WorkingDada**

### CODE REVIEW

**Comment by WorkingDada** [comment]
### Profile View Page
This page is at `https://localhost:3000/view-profile/[userID]` 

1. Added section to view User's profile
2. Added info section of User's profile
3. Gallery preview of User's created galleries

**Comment by WorkingDada** [comment]
image

**Comment by WorkingDada** [comment]
1*4bw__q_YPonUBVfnEymj8A

**Comment by mekintown** [comment]
Looks good kub

**Pull request merged**
